"""mvp initial schema

Revision ID: bf7b10741d97
Revises: 
Create Date: 2026-08-05 10:00:09.979218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7b10741d97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('notification_agreed', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('devices',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('push_token', name=op.f('uq_devices_push_token'))
    )
    op.create_table('foods',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_foods_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    op.create_table('products',
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('KURLY', 'N_MART', name='source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_products_food_id_foods'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('source', 'external_id', name='uq_products_source_external_id')
    )
    op.create_table('product_freshness_profiles',
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('storage_type', sa.Enum('REFRIGERATED', 'FROZEN', 'ROOM_TEMPERATURE', name='storage_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expiration_days', sa.SmallInteger(), nullable=False),
    sa.Column('expiration_source', sa.Enum('USER_INPUT', 'PACKAGE_OCR', 'PRODUCT_DISCLOSURE', 'MFDS_REFERENCE', name='expiration_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expiration_status', sa.Enum('CONFIRMED', 'ESTIMATED', 'REVIEW_REQUIRED', name='expiration_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_product_freshness_profiles_food_id_foods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_freshness_profiles_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_freshness_profiles'))
    )
    op.create_index('ix_product_freshness_profiles_expiration_status', 'product_freshness_profiles', ['expiration_status'], unique=False)
    op.create_index('ix_product_freshness_profiles_food_id', 'product_freshness_profiles', ['food_id'], unique=False)
    op.create_index('ix_product_freshness_profiles_product_id', 'product_freshness_profiles', ['product_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('freshness_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('storage_type', sa.Enum('REFRIGERATED', 'FROZEN', 'ROOM_TEMPERATURE', name='storage_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('expiration_source', sa.Enum('USER_INPUT', 'PACKAGE_OCR', 'PRODUCT_DISCLOSURE', 'MFDS_REFERENCE', name='expiration_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('expiration_status', sa.Enum('CONFIRMED', 'ESTIMATED', 'REVIEW_REQUIRED', name='expiration_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deletion_reason', sa.Enum('CONSUMED', 'DISCARDED', 'WRONG_ENTRY', name='deletion_reason', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_deleted = false AND deletion_reason IS NULL) OR (is_deleted = true AND deletion_reason IS NOT NULL)', name=op.f('ck_ingredients_deletion_reason_matches_is_deleted')),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_ingredients_food_id_foods'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['freshness_profile_id'], ['product_freshness_profiles.id'], name=op.f('fk_ingredients_freshness_profile_id_product_freshness_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_ingredients_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ingredients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_index('ix_ingredients_user_id_is_deleted', 'ingredients', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_ingredients_user_id_storage_type_expiration_date', 'ingredients', ['user_id', 'storage_type', 'expiration_date'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_notifications_ingredient_id_ingredients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_index('ix_ingredients_user_id_storage_type_expiration_date', table_name='ingredients')
    op.drop_index('ix_ingredients_user_id_is_deleted', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index('ix_product_freshness_profiles_product_id', table_name='product_freshness_profiles')
    op.drop_index('ix_product_freshness_profiles_food_id', table_name='product_freshness_profiles')
    op.drop_index('ix_product_freshness_profiles_expiration_status', table_name='product_freshness_profiles')
    op.drop_table('product_freshness_profiles')
    op.drop_table('products')
    op.drop_table('foods')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
