"""add product_image_embeddings table

Revision ID: c19da379d11d
Revises: 63ff83cd4639
Create Date: 2026-09-19 22:16:16.564567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c19da379d11d'
down_revision: Union[str, Sequence[str], None] = '63ff83cd4639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ingredients.storage_type/deletion_reason 타입 drift는 이 revision과 무관한
    # 기존 이슈라 autogenerate 결과에서 제외했다(별도로 다뤄야 함).
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('product_image_embeddings',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_image_embeddings_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_image_embeddings')),
    sa.UniqueConstraint('product_id', 'image_hash', 'model_version', name='uq_product_image_embeddings')
    )
    op.create_index('ix_product_image_embeddings_embedding_cosine', 'product_image_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_image_embeddings_embedding_cosine', table_name='product_image_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('product_image_embeddings')
    # vector 확장은 다른 테이블이 쓸 수도 있으니 downgrade에서 DROP EXTENSION하지 않는다.
    # ### end Alembic commands ###
