"""add notifications is_read

Revision ID: f003b97d7bda
Revises: bf7b10741d97
Create Date: 2026-08-05 10:30:18.523428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f003b97d7bda'
down_revision: Union[str, Sequence[str], None] = 'bf7b10741d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default를 명시해 기존 row가 있어도 NOT NULL 컬럼 추가가 안전하게 끝나도록 한다.
    op.add_column(
        'notifications',
        sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###
