"""로컬 개발용 seed 데이터 정의 (BE-6).

여기 있는 값(email, push_token, 카테고리/식품 이름, 상품 외부 ID, ingredient name)은
idempotent get-or-create와 reset 범위 제한에 쓰는 고정 식별자다. 값을 바꾸면
재실행 시 새 행이 생길 수 있으니 함부로 바꾸지 않는다.

목업 정책(`dev_docs/mock_data_policy.md`):
- 표시명 `[MOCK]` 접두어
- URL은 `example.invalid`
- 상품 external_id는 `MOCK-*`
"""

from typing import Any

# FE 로컬 로그인용. runner가 hash_password로 해싱한다.
SEED_PASSWORD = "seedpass123"

SEED_USERS: list[dict[str, Any]] = [
    {
        "email": "seed.user1@example.invalid",
        "nickname": "시드유저1",
        "notification_agreed": True,
    },
    {
        "email": "seed.user2@example.invalid",
        "nickname": "시드유저2",
        "notification_agreed": False,
    },
    {
        "email": "seed.user3@example.invalid",
        "nickname": "시드유저3",
        "notification_agreed": True,
    },
]
SEED_USER_EMAILS: list[str] = [u["email"] for u in SEED_USERS]

SEED_DEVICES: list[dict[str, Any]] = [
    {"user_email": "seed.user1@example.invalid", "push_token": "MOCK-device-token-1"},
    {"user_email": "seed.user2@example.invalid", "push_token": "MOCK-device-token-2"},
    {"user_email": "seed.user3@example.invalid", "push_token": "MOCK-device-token-3"},
]

SEED_CATEGORY_NAMES: list[str] = ["유제품", "채소", "가공식품", "육류", "해산물", "과자"]

SEED_FOODS: list[dict[str, Any]] = [
    {"name": "우유", "category_name": "유제품"},
    {"name": "계란", "category_name": "유제품"},
    {"name": "요거트", "category_name": "유제품"},
    {"name": "양파", "category_name": "채소"},
    {"name": "당근", "category_name": "채소"},
    {"name": "시금치", "category_name": "채소"},
    {"name": "즉석밥", "category_name": "가공식품"},
    {"name": "냉동만두", "category_name": "가공식품"},
    {"name": "닭가슴살", "category_name": "육류"},
    {"name": "돼지고기", "category_name": "육류"},
    {"name": "고등어", "category_name": "해산물"},
    {"name": "새우", "category_name": "해산물"},
    {"name": "과자", "category_name": "과자"},
]

SEED_PRODUCTS: list[dict[str, Any]] = [
    {
        "external_id": "MOCK-1001",
        "source": "KURLY",
        "name": "[MOCK] 컬리 우유 1L",
        "food_name": "우유",
    },
    {
        "external_id": "MOCK-1002",
        "source": "KURLY",
        "name": "[MOCK] 컬리 계란 15구",
        "food_name": "계란",
    },
    {
        "external_id": "MOCK-1003",
        "source": "KURLY",
        "name": "[MOCK] 컬리 요거트",
        "food_name": "요거트",
    },
    {
        "external_id": "MOCK-2001",
        "source": "N_MART",
        "name": "[MOCK] N마트 양파 1kg",
        "food_name": "양파",
    },
    {
        "external_id": "MOCK-2002",
        "source": "N_MART",
        "name": "[MOCK] N마트 당근 500g",
        "food_name": "당근",
    },
    {
        "external_id": "MOCK-2003",
        "source": "N_MART",
        "name": "[MOCK] N마트 시금치",
        "food_name": "시금치",
    },
    {
        "external_id": "MOCK-1004",
        "source": "KURLY",
        "name": "[MOCK] 컬리 즉석밥",
        "food_name": "즉석밥",
    },
    {
        "external_id": "MOCK-1005",
        "source": "KURLY",
        "name": "[MOCK] 컬리 냉동만두",
        "food_name": "냉동만두",
    },
    {
        "external_id": "MOCK-3001",
        "source": "KURLY",
        "name": "[MOCK] 컬리 닭가슴살",
        "food_name": "닭가슴살",
    },
    {
        "external_id": "MOCK-3002",
        "source": "N_MART",
        "name": "[MOCK] N마트 돼지고기",
        "food_name": "돼지고기",
    },
    {
        "external_id": "MOCK-4001",
        "source": "KURLY",
        "name": "[MOCK] 컬리 고등어",
        "food_name": "고등어",
    },
    {
        "external_id": "MOCK-4002",
        "source": "N_MART",
        "name": "[MOCK] N마트 새우",
        "food_name": "새우",
    },
    # 실바코드 예시(화면 테스트용 EAN). 인식 시 external_id로 매칭된다.
    {
        "external_id": "8809841063326",
        "source": "N_MART",
        "name": "스낵 과자",
        "food_name": "과자",
    },
    # 시나리오: 비활성 상품 — products 테이블에 is_active가 없어
    # "어떤 ingredient/프로필에도 연결되지 않은 카탈로그 행"으로 근사한다.
    {
        "external_id": "MOCK-INACTIVE",
        "source": "KURLY",
        "name": "[MOCK] 단종 상품(비활성)",
        "food_name": "즉석밥",
    },
]

# food_name + product_external_id 조합으로 ingredient가 참조한다.
# storage_type은 freshness 프로필용 문자열 enum(REFRIGERATED/FROZEN/...).
SEED_FRESHNESS_PROFILES: list[dict[str, Any]] = [
    {
        "food_name": "우유",
        "product_external_id": "MOCK-1001",
        "storage_type": "REFRIGERATED",
        "expiration_days": 10,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
    },
    {
        "food_name": "냉동만두",
        "product_external_id": "MOCK-1005",
        "storage_type": "FROZEN",
        "expiration_days": 180,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
    },
    {
        "food_name": "즉석밥",
        "product_external_id": "MOCK-1004",
        "storage_type": "ROOM_TEMPERATURE",
        "expiration_days": 365,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
    },
    {
        "food_name": "닭가슴살",
        "product_external_id": "MOCK-3001",
        "storage_type": "FROZEN",
        "expiration_days": 90,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
    },
    {
        "food_name": "고등어",
        "product_external_id": "MOCK-4001",
        "storage_type": "REFRIGERATED",
        "expiration_days": 3,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
    },
]

# key는 notification 연결용 seed 내부 식별자(DB 컬럼 아님).
# name은 멱등 키(user_id + name). 같은 유저에 같은 name이 두 번 있으면 안 된다.
#
# 필수 시나리오 5종:
# 1) 냉장 확정  2) 냉동 예상  3) 프로필 없음(직접입력)
# 4) 비활성 상품(SEED_PRODUCTS의 MOCK-INACTIVE)  5) 소비기한 임박
SEED_INGREDIENTS: list[dict[str, Any]] = [
    # --- user1 활성 12건: 3D/대시보드용 (냉장·냉동·임박·만료·여유) ---
    {
        "key": "user1-milk-confirmed",
        "user_email": "seed.user1@example.invalid",
        "food_name": "우유",
        "product_external_id": "MOCK-1001",
        "use_profile": True,
        "name": "[MOCK] 우유 (냉장확정)",
        "storage_type": 0,
        "quantity": 1,
        "unit": "개",
        "expiration_offset_days": 8,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/milk.jpg",
        "is_deleted": False,
        "deletion_reason": None,
        "scenario": "냉장 확정",
    },
    {
        "key": "user1-dumpling-frozen-estimated",
        "user_email": "seed.user1@example.invalid",
        "food_name": "냉동만두",
        "product_external_id": "MOCK-1005",
        "use_profile": True,
        "name": "[MOCK] 냉동만두 (냉동예상)",
        "storage_type": 1,
        "quantity": 1,
        "unit": "봉",
        "expiration_offset_days": 120,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
        "image_url": "https://example.invalid/mock/dumpling.jpg",
        "is_deleted": False,
        "deletion_reason": None,
        "scenario": "냉동 예상",
    },
    {
        "key": "user1-onion-direct",
        "user_email": "seed.user1@example.invalid",
        "food_name": "양파",
        "product_external_id": None,
        "use_profile": False,
        "name": "[MOCK] 양파 (직접입력)",
        "storage_type": 0,
        "quantity": 3,
        "unit": "개",
        "expiration_offset_days": 14,
        "expiration_source": "USER_INPUT",
        "expiration_status": "ESTIMATED",
        "image_url": None,
        "is_deleted": False,
        "deletion_reason": None,
        "scenario": "프로필 없음(직접입력)",
    },
    {
        "key": "user1-mackerel-expiring",
        "user_email": "seed.user1@example.invalid",
        "food_name": "고등어",
        "product_external_id": "MOCK-4001",
        "use_profile": True,
        "name": "[MOCK] 고등어 (임박)",
        "storage_type": 0,
        "quantity": 2,
        "unit": "마리",
        "expiration_offset_days": 2,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/mackerel.jpg",
        "is_deleted": False,
        "deletion_reason": None,
        "scenario": "소비기한 임박",
    },
    {
        "key": "user1-yogurt-expiring",
        "user_email": "seed.user1@example.invalid",
        "food_name": "요거트",
        "product_external_id": "MOCK-1003",
        "use_profile": False,
        "name": "[MOCK] 요거트 (임박)",
        "storage_type": 0,
        "quantity": 2,
        "unit": "개",
        "expiration_offset_days": 1,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/yogurt.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-spinach-overdue",
        "user_email": "seed.user1@example.invalid",
        "food_name": "시금치",
        "product_external_id": "MOCK-2003",
        "use_profile": False,
        "name": "[MOCK] 시금치 (만료)",
        "storage_type": 0,
        "quantity": 1,
        "unit": "단",
        "expiration_offset_days": -2,
        "expiration_source": "USER_INPUT",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/spinach.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-carrot-ok",
        "user_email": "seed.user1@example.invalid",
        "food_name": "당근",
        "product_external_id": "MOCK-2002",
        "use_profile": False,
        "name": "[MOCK] 당근",
        "storage_type": 0,
        "quantity": 4,
        "unit": "개",
        "expiration_offset_days": 20,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
        "image_url": "https://example.invalid/mock/carrot.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-chicken-frozen",
        "user_email": "seed.user1@example.invalid",
        "food_name": "닭가슴살",
        "product_external_id": "MOCK-3001",
        "use_profile": True,
        "name": "[MOCK] 닭가슴살 (냉동)",
        "storage_type": 1,
        "quantity": 1,
        "unit": "팩",
        "expiration_offset_days": 60,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/chicken.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-pork-frozen",
        "user_email": "seed.user1@example.invalid",
        "food_name": "돼지고기",
        "product_external_id": "MOCK-3002",
        "use_profile": False,
        "name": "[MOCK] 돼지고기 (냉동)",
        "storage_type": 1,
        "quantity": 1,
        "unit": "팩",
        "expiration_offset_days": 45,
        "expiration_source": "USER_INPUT",
        "expiration_status": "ESTIMATED",
        "image_url": "https://example.invalid/mock/pork.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-shrimp-frozen",
        "user_email": "seed.user1@example.invalid",
        "food_name": "새우",
        "product_external_id": "MOCK-4002",
        "use_profile": False,
        "name": "[MOCK] 새우 (냉동)",
        "storage_type": 1,
        "quantity": 1,
        "unit": "팩",
        "expiration_offset_days": 30,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/shrimp.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-egg-ok",
        "user_email": "seed.user1@example.invalid",
        "food_name": "계란",
        "product_external_id": "MOCK-1002",
        "use_profile": False,
        "name": "[MOCK] 계란",
        "storage_type": 0,
        "quantity": 10,
        "unit": "구",
        "expiration_offset_days": 12,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": "https://example.invalid/mock/egg.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user1-rice-ok",
        "user_email": "seed.user1@example.invalid",
        "food_name": "즉석밥",
        "product_external_id": "MOCK-1004",
        "use_profile": True,
        "name": "[MOCK] 즉석밥",
        "storage_type": 0,
        "quantity": 3,
        "unit": "개",
        "expiration_offset_days": 200,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
        "image_url": "https://example.invalid/mock/rice.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    # --- soft-delete 샘플 (통계/가시성 테스트) ---
    {
        "key": "user1-egg-consumed",
        "user_email": "seed.user1@example.invalid",
        "food_name": "계란",
        "product_external_id": "MOCK-1002",
        "use_profile": False,
        "name": "[MOCK] 계란 (소비완료)",
        "storage_type": 0,
        "quantity": 1,
        "expiration_offset_days": -10,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "CONFIRMED",
        "image_url": None,
        "is_deleted": True,
        "deletion_reason": "CONSUMED",
    },
    {
        "key": "user2-carrot-ok",
        "user_email": "seed.user2@example.invalid",
        "food_name": "당근",
        "product_external_id": "MOCK-2002",
        "use_profile": False,
        "name": "[MOCK] 당근 (user2)",
        "storage_type": 0,
        "quantity": 2,
        "unit": "개",
        "expiration_offset_days": 25,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
        "image_url": "https://example.invalid/mock/carrot-u2.jpg",
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user2-dumpling-discarded",
        "user_email": "seed.user2@example.invalid",
        "food_name": "냉동만두",
        "product_external_id": "MOCK-1005",
        "use_profile": True,
        "name": "[MOCK] 냉동만두 (폐기)",
        "storage_type": 1,
        "quantity": 1,
        "expiration_offset_days": 100,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
        "image_url": None,
        "is_deleted": True,
        "deletion_reason": "DISCARDED",
    },
    {
        "key": "user3-onion-overdue",
        "user_email": "seed.user3@example.invalid",
        "food_name": "양파",
        "product_external_id": None,
        "use_profile": False,
        "name": "[MOCK] 양파 (user3 만료)",
        "storage_type": 0,
        "quantity": 1,
        "expiration_offset_days": -3,
        "expiration_source": "USER_INPUT",
        "expiration_status": "CONFIRMED",
        "image_url": None,
        "is_deleted": False,
        "deletion_reason": None,
    },
    {
        "key": "user3-rice-incorrect",
        "user_email": "seed.user3@example.invalid",
        "food_name": "즉석밥",
        "product_external_id": "MOCK-1004",
        "use_profile": True,
        "name": "[MOCK] 즉석밥 (오등록)",
        "storage_type": 0,
        "quantity": 1,
        "expiration_offset_days": 300,
        "expiration_source": "PRODUCT_DISCLOSURE",
        "expiration_status": "ESTIMATED",
        "image_url": None,
        "is_deleted": True,
        "deletion_reason": "INCORRECT_ENTRY",
    },
]

SEED_NOTIFICATIONS: list[dict[str, Any]] = [
    {
        "user_email": "seed.user1@example.invalid",
        "ingredient_key": "user1-mackerel-expiring",
        "message": "[MOCK] 고등어의 소비기한이 얼마 남지 않았어요.",
        "is_read": False,
    },
    {
        "user_email": "seed.user1@example.invalid",
        "ingredient_key": "user1-yogurt-expiring",
        "message": "[MOCK] 요거트가 곧 소비기한입니다.",
        "is_read": False,
    },
    {
        "user_email": "seed.user1@example.invalid",
        "ingredient_key": "user1-egg-consumed",
        "message": "[MOCK] 계란을 소비 완료로 기록했어요.",
        "is_read": True,
    },
    {
        "user_email": "seed.user2@example.invalid",
        "ingredient_key": "user2-carrot-ok",
        "message": "[MOCK] 당근이 냉장 보관 중이에요.",
        "is_read": False,
    },
    {
        "user_email": "seed.user3@example.invalid",
        "ingredient_key": "user3-rice-incorrect",
        "message": "[MOCK] 즉석밥 등록 정보를 확인해주세요.",
        "is_read": True,
    },
]
